version: '3.0'

services:
  angular:
    build: frontend
    ports:
      - '80:80'
    expose:
      - '80'
    # volumes:
    # - ./angular-nginx.conf:/etc/nginx/conf.d/default.conf

  express:
    build: backend
    environment:
      PORT: 80
      MONGODB_HOST: mongo
    expose:
      - '80'
    links:
      - database

  database:
    container_name: mongo
    image: mongo
    expose:
      - '27017'
    # volumes:
    # - ./localFolder:/data/db
